### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by sdieedu** [Senkita/Science_Reading_Book_Downloader#3]
9787030085405
微积分和数学分析引论 第二卷（第二分册）
同系列多本书不行，例如：输入ID
B92BAF9247CAAB185E053010B0A0AB39B00B
直接提示：输入有误，请重新输入。
然而：书可以网页直接阅读打开，书浏览的时候，先出来对话框：文件过大，需要等待一段时间。（其实很快就打开了）
怀疑爬虫需要过开始对话框。
还有：这个ID为啥程序不识别？

**Comment by Senkita** [comment]
> 9787030085405 微积分和数学分析引论 第二卷（第二分册） 同系列多本书不行，例如：输入ID B92BAF9247CAAB185E053010B0A0AB39B00B 直接提示：输入有误，请重新输入。 然而：书可以网页直接阅读打开，书浏览的时候，先出来对话框：文件过大，需要等待一段时间。（其实很快就打开了） 怀疑爬虫需要过开始对话框。 还有：这个ID为啥程序不识别？

这个爬虫的原理是直接访问其文档预览的图片提供接口，与它家WebPDF Viewer同源，并不是去模拟浏览器操作。
说人话呢，就是科学文库的网站管理员过于勤奋，又双叒叕把接口换了。
唉，跟着改好累，暂时弃了。
